#!/bin/bash

echo '******************************'
echo *Bonjour $(uname -n)*
echo "*        $(date "+Il est %Hh%M")        *"
echo '******************************'

echo -e "      ******************************
      *Bonjour $(uname -n)*
      *        $(date "+Il est %Hh%M")        *
      ******************************"


